### ISSUE TITLE
Not showing on Invoice (Magento 2.0.7)

### ISSUE THREAD

**Issue by plauge** [Mestrona/Mestrona_BundleCustomOptions#2]
In Magento 2.0.7 I can save the Custom Options. (The "We can't save custom-defined options for bundles with dynamic pricing" is stil there.)

The Custom Options shows up on the Product Page, the Cart, the order mail, the invoice mail.
It also show under Sales in Mageto backend. But only until I create the invoice. Then all the info from Custom Options disappears in the backend.

**Comment by amenk** [comment]
Is this still happening in 2.1.1 ?

**Comment by plauge** [comment]
Let me test it.

**Comment by plauge** [comment]
Hm - I can not test due to there is stil no button in 2.1.1 :-)

**Comment by amenk** [comment]
Should be fixed
